### ISSUE TITLE
New article amount limit

### ISSUE THREAD

**Issue by noamiz5060** [jordibc/entrez#4]
Hello hello
I've been using the classic article function which returns the articles for a string
![image](https://user-images.githubusercontent.com/111743864/216772373-53557f61-6314-4b04-82b9-db1aaaa2b75f.png)

I've noticed now that there's a limit to the amount of articles I receive (not the one I put in retmax).
The amount I get is 9999 PMIDS, for key words who used to return 100k PMIDS (T cell for example)

![image](https://user-images.githubusercontent.com/111743864/216772495-ad60d957-fb2f-4bb2-a914-9aeebaa8a1ad.png)
The amount I get now

![image](https://user-images.githubusercontent.com/111743864/216772506-5779bc40-b786-4d60-b28c-d6043106d723.png)
The amount I used to get

**Comment by jordibc** [comment]
@noamiz5060 I think that you are using a different package, probably https://biopython.org/docs/1.74/api/Bio.Entrez.html

But if I have to guess, maybe the NCBI site is not allowing more than 9999 results now...
